openapi: 3.0.0
info:
  title: User Verification API
  version: 1.0.0
paths:
  /verify-user:
    post:
      summary: Verify if a user exists
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
      responses:
        '200':
          description: User verification result
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
