openapi: 3.0.0
info:
  title: User Checker API
  version: 1.0.0
servers:
  - url: https://userlookupapi.westus2.cloudapp.azure.com
    description: Production server (uses live data)
paths:
  /checkUser:
    get:
      summary: Check if a user exists
      parameters:
        - in: query
          name: username
          schema:
            type: string
          required: true
          description: Username to check
      responses:
        '200':
          description: User existence result
          content:
            application/json:
              example:
                message: User exists
        '404':
          description: User not found
          content:
            application/json:
              example:
                message: User does not exist
